"use client";

import { useState } from "react";
import {
  BarChart as BarChartIcon,
  CheckCircle,
  Clock,
  Download,
  FileText,
  ShieldAlert,
  TrendingUp,
} from "lucide-react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { toast } from "sonner";

import { PageHeading } from "@/components/layout/page-heading";
import { OfflineSampleNotice } from "@/components/ui/offline-sample-notice";
import { Panel } from "@/components/ui/panel";
import { useSession } from "@/lib/auth";
import { reportChartData, initialReports } from "@/mocks/reports";
import type { Report } from "@/types";

export default function ReportsPage() {
  const session = useSession();
  const [reports, setReports] = useState<Report[]>(initialReports);
  const [typeFilter, setTypeFilter] = useState("All");

  const filteredReports =
    typeFilter === "All"
      ? reports
      : reports.filter((report) => report.type === typeFilter);

  const generateReport = () => {
    const newReport: Report = {
      id: `RPT-2026-${916 + reports.length}`,
      name: "New Cybercrime Intelligence Report",
      type: "Risk Analysis",
      generated: new Date().toLocaleString("en-IN"),
      generatedBy: session?.name ?? "Officer",
      status: "Ready",
    };

    setReports([newReport, ...reports]);
    toast.success("Report generated successfully");
  };

  const downloadReport = (report: Report) => {
    const content =
      `Cybercrime Intelligence Report\n\n` +
      `Report ID: ${report.id}\n` +
      `Report Name: ${report.name}\n` +
      `Type: ${report.type}\n` +
      `Generated: ${report.generated}\n` +
      `Generated By: ${report.generatedBy}\n` +
      `Status: ${report.status}\n`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.id}.txt`;
    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <PageHeading
        title="Reports"
        description="Generate and review cybercrime intelligence and analytical reports"
      />

      <OfflineSampleNotice />

      <div className="flex items-center gap-3 rounded-lg border border-l-4 border-border border-l-primary bg-secondary p-4">
        <div className="flex size-9 shrink-0 items-center justify-center rounded-md bg-accent text-primary">
          <TrendingUp className="size-4" />
        </div>
        <div>
          <strong className="block text-sm text-foreground">
            Intelligence Reporting Overview
          </strong>
          <p className="mt-0.5 text-xs text-muted-foreground">
            Reports provide analytical insights for cybercrime investigation
            and proactive intervention.
          </p>
        </div>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex h-9 items-center gap-2 rounded-md border border-border bg-card px-3 text-sm text-muted-foreground">
          <FileText className="size-4" />
          <select
            className="bg-transparent text-sm outline-none"
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
          >
            <option value="All">All Report Types</option>
            <option value="Risk Analysis">Risk Analysis</option>
            <option value="Prediction">Prediction</option>
            <option value="GIS Intelligence">GIS Intelligence</option>
          </select>
        </div>

        <button
          type="button"
          className="flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-white"
          onClick={generateReport}
        >
          <BarChartIcon className="size-4" /> Generate Report
        </button>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {[
          {
            icon: FileText,
            top: "border-t-primary",
            iconBg: "bg-accent text-primary",
            label: "Total Reports",
            value: reports.length,
            note: "Generated",
          },
          {
            icon: CheckCircle,
            top: "border-t-green-600",
            iconBg: "bg-green-100 text-green-700",
            label: "Ready Reports",
            value: reports.filter((r) => r.status === "Ready").length,
            note: "Available",
          },
          {
            icon: ShieldAlert,
            top: "border-t-orange-500",
            iconBg: "bg-orange-100 text-orange-700",
            label: "High Risk Cases",
            value: 186,
            note: "Require attention",
          },
          {
            icon: Clock,
            top: "border-t-[#7256a5]",
            iconBg: "bg-purple-100 text-purple-700",
            label: "Last Updated",
            value: "15:30",
            note: "Today",
          },
        ].map(({ icon: Icon, top, iconBg, label, value, note }) => (
          <div
            key={label}
            className={`rounded-lg border border-border border-t-4 bg-card p-4 shadow-sm ${top}`}
          >
            <div className="flex items-center gap-3">
              <div
                className={`flex size-10 items-center justify-center rounded-md ${iconBg}`}
              >
                <Icon className="size-5" />
              </div>
              <div>
                <span className="block text-xs text-muted-foreground">
                  {label}
                </span>
                <strong className="block text-xl text-foreground">
                  {value}
                </strong>
                <small className="block text-xs text-muted-foreground">
                  {note}
                </small>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="grid gap-6 xl:grid-cols-2">
        <Panel
          icon={BarChartIcon}
          title="Cases by Crime Category"
          subtitle="Current reported cybercrime distribution"
          actions={
            <span className="rounded bg-accent px-2 py-1 text-[10px] font-semibold text-primary">
              SAMPLE DATA
            </span>
          }
        >
          <div className="h-72 p-3">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={reportChartData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                <YAxis tick={{ fontSize: 12 }} />
                <Tooltip />
                <Bar dataKey="cases" fill="#1671b8" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        <Panel icon={FileText} title="Report Information" subtitle="Intelligence reporting status">
          <div className="p-5">
            {[
              ["Data coverage", "Pune District"],
              ["Prediction window", "Next 24 Hours"],
              ["Reports generated", `${reports.length} Reports`],
            ].map(([label, value]) => (
              <div
                key={label}
                className="flex items-center justify-between border-b border-border py-3 last:border-0"
              >
                <span className="text-sm text-muted-foreground">{label}</span>
                <strong className="text-sm text-foreground">{value}</strong>
              </div>
            ))}
            <div className="flex items-center justify-between py-3">
              <span className="text-sm text-muted-foreground">
                Intelligence status
              </span>
              <span className="rounded-full bg-green-100 px-2.5 py-1 text-[10px] font-bold text-green-700">
                ACTIVE
              </span>
            </div>
          </div>
        </Panel>
      </div>

      <Panel
        icon={FileText}
        title="Generated Reports"
        subtitle="Previously generated intelligence reports"
        actions={
          <span className="rounded bg-muted px-2 py-1 text-[11px] text-muted-foreground">
            {filteredReports.length} records
          </span>
        }
      >
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border text-left text-xs uppercase text-muted-foreground">
                <th className="px-5 py-3">Report ID</th>
                <th className="px-5 py-3">Report Name</th>
                <th className="px-5 py-3">Type</th>
                <th className="px-5 py-3">Generated</th>
                <th className="px-5 py-3">Generated By</th>
                <th className="px-5 py-3">Status</th>
                <th className="px-5 py-3">Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredReports.map((report) => (
                <tr
                  key={report.id}
                  className="border-b border-border last:border-0 hover:bg-muted/50"
                >
                  <td className="px-5 py-3 font-semibold text-primary">
                    {report.id}
                  </td>
                  <td className="px-5 py-3 font-medium">{report.name}</td>
                  <td className="px-5 py-3">
                    <span className="rounded bg-secondary px-2 py-1 text-xs font-semibold text-primary">
                      {report.type}
                    </span>
                  </td>
                  <td className="px-5 py-3">{report.generated}</td>
                  <td className="px-5 py-3">{report.generatedBy}</td>
                  <td className="px-5 py-3">
                    <span className="rounded-full bg-green-100 px-2.5 py-1 text-xs font-semibold text-green-700">
                      {report.status}
                    </span>
                  </td>
                  <td className="px-5 py-3">
                    <button
                      type="button"
                      className="flex items-center gap-1.5 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-primary"
                      onClick={() => downloadReport(report)}
                    >
                      <Download className="size-3.5" /> Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>

      <div className="flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">
        <ShieldAlert className="size-4 shrink-0 text-amber-700" />
        <span>
          <strong className="text-amber-800">Security Notice:</strong> Reports
          contain restricted law-enforcement intelligence. Access and downloads
          are recorded in the Audit Logs.
        </span>
      </div>
    </div>
  );
}