"use client";

import { useState } from "react";
import Link from "next/link";
import {
  AlertTriangle,
  Bell,
  CheckCircle,
  Clock,
  Eye,
  Filter,
  RefreshCw,
  Search,
} from "lucide-react";
import { toast } from "sonner";

import { PageHeading } from "@/components/layout/page-heading";
import { SeverityBadge, StatusBadge } from "@/components/badges";
import { Panel } from "@/components/ui/panel";
import { StatCard } from "@/components/ui/stat-card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { initialAlerts } from "@/mocks/alerts";
import type { AlertSummary } from "@/types";

export default function AlertsPage() {
  const [alerts, setAlerts] = useState(initialAlerts);
  const [search, setSearch] = useState("");
  const [severityFilter, setSeverityFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const [selectedAlert, setSelectedAlert] = useState<AlertSummary | null>(null);

  const filteredAlerts = alerts.filter((alert) => {
    const matchesSearch =
      alert.id.toLowerCase().includes(search.toLowerCase()) ||
      alert.type.toLowerCase().includes(search.toLowerCase()) ||
      alert.location.toLowerCase().includes(search.toLowerCase());

    const matchesSeverity =
      severityFilter === "All" || alert.severity === severityFilter.toLowerCase();

    const matchesStatus =
      statusFilter === "All" || alert.status === statusFilter.toLowerCase();

    return matchesSearch && matchesSeverity && matchesStatus;
  });

  const updateAlert = (alertId: string, status: AlertSummary["status"]) => {
    setAlerts((previous) =>
      previous.map((alert) =>
        alert.id === alertId ? { ...alert, status } : alert
      )
    );

    setSelectedAlert((previous) =>
      previous && previous.id === alertId ? { ...previous, status } : previous
    );

    toast.success(
      status === "acknowledged"
        ? `${alertId} acknowledged successfully.`
        : `${alertId} marked as resolved.`
    );
  };

  const activeCount = alerts.filter((a) => a.status !== "resolved").length;
  const highSeverityCount = alerts.filter((a) => a.severity === "high").length;
  const unacknowledgedCount = alerts.filter(
    (a) => a.status === "unacknowledged"
  ).length;
  const resolvedCount = alerts.filter((a) => a.status === "resolved").length;

  return (
    <div className="space-y-6">
      <PageHeading
        title="Alert Management"
        description="Monitor and respond to real-time cybercrime intelligence alerts"
      >
        <span>Last Updated: 16 Sep 2026, 03:31 PM</span>
        <button
          type="button"
          className="flex size-8 items-center justify-center rounded-md border border-border bg-card text-muted-foreground"
        >
          <RefreshCw className="size-4" />
        </button>
      </PageHeading>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          icon={Bell}
          tone="blue"
          value={String(activeCount)}
          label="Active Alerts"
          note="Requires monitoring"
        />
        <StatCard
          icon={AlertTriangle}
          tone="red"
          value={String(highSeverityCount)}
          label="High Severity"
          note="Immediate attention"
        />
        <StatCard
          icon={Clock}
          tone="orange"
          value={String(unacknowledgedCount)}
          label="Unacknowledged"
          note="Awaiting officer action"
        />
        <StatCard
          icon={CheckCircle}
          tone="green"
          value={String(resolvedCount)}
          label="Resolved"
          note="Alerts closed"
        />
      </div>

      <Panel
        icon={Bell}
        title="Active Intelligence Alerts"
        subtitle="Real-time alerts generated by the predictive engine"
      >
        <div className="flex flex-wrap items-center gap-3 border-b border-border px-5 py-4">
          <div className="relative">
            <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              className="w-64 pl-9"
              placeholder="Search alert ID, type or location..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          <div className="relative">
            <Filter className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
            <select
              className="h-9 rounded-md border border-input bg-background pl-9 pr-3 text-sm"
              value={severityFilter}
              onChange={(e) => setSeverityFilter(e.target.value)}
            >
              <option value="All">All Severity</option>
              <option value="High">High</option>
              <option value="Medium">Medium</option>
              <option value="Low">Low</option>
            </select>
          </div>

          <select
            className="h-9 rounded-md border border-input bg-background px-3 text-sm"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="All">All Status</option>
            <option value="Unacknowledged">Unacknowledged</option>
            <option value="Acknowledged">Acknowledged</option>
            <option value="Resolved">Resolved</option>
          </select>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border text-left text-xs uppercase text-muted-foreground">
                <th className="px-5 py-3">Alert ID</th>
                <th className="px-5 py-3">Time</th>
                <th className="px-5 py-3">Alert Type</th>
                <th className="px-5 py-3">Location</th>
                <th className="px-5 py-3">Severity</th>
                <th className="px-5 py-3">Status</th>
                <th className="px-5 py-3">Case</th>
                <th className="px-5 py-3">Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredAlerts.map((alert) => (
                <tr
                  key={alert.id}
                  className="border-b border-border last:border-0 hover:bg-muted/50"
                >
                  <td className="px-5 py-3 font-semibold text-primary">
                    {alert.id}
                  </td>
                  <td className="px-5 py-3">{alert.time}</td>
                  <td className="px-5 py-3">{alert.type}</td>
                  <td className="px-5 py-3">{alert.location}</td>
                  <td className="px-5 py-3">
                    <SeverityBadge level={alert.severity} />
                  </td>
                  <td className="px-5 py-3">
                    <StatusBadge status={alert.status} />
                  </td>
                  <td className="px-5 py-3">
                    <Link
                      href={`/cases/${alert.caseId}`}
                      className="font-semibold text-primary"
                    >
                      {alert.caseId}
                    </Link>
                  </td>
                  <td className="px-5 py-3">
                    <div className="flex items-center gap-2">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => setSelectedAlert(alert)}
                      >
                        <Eye className="size-3.5" /> View
                      </Button>
                      {alert.status === "unacknowledged" && (
                        <Button
                          size="sm"
                          onClick={() => updateAlert(alert.id, "acknowledged")}
                        >
                          Acknowledge
                        </Button>
                      )}
                      {alert.status === "acknowledged" && (
                        <Button
                          size="sm"
                          className="bg-green-700 hover:bg-green-800"
                          onClick={() => updateAlert(alert.id, "resolved")}
                        >
                          Resolve
                        </Button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {filteredAlerts.length === 0 && (
            <div className="py-10 text-center text-sm text-muted-foreground">
              No alerts found matching your filters.
            </div>
          )}
        </div>
      </Panel>

      <div className="flex items-start gap-3 rounded-lg border border-border bg-secondary p-4">
        <AlertTriangle className="mt-0.5 size-4 shrink-0 text-primary" />
        <div>
          <strong className="block text-sm text-foreground">
            Intelligence Alert Notice
          </strong>
          <span className="text-xs leading-relaxed text-muted-foreground">
            Alerts shown here are generated from predictive analytics and
            should be verified by authorized personnel before operational
            action.
          </span>
        </div>
      </div>

      <Dialog
        open={selectedAlert !== null}
        onOpenChange={(open) => {
          if (!open) setSelectedAlert(null);
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Alert Details</DialogTitle>
            <DialogDescription>{selectedAlert?.id}</DialogDescription>
          </DialogHeader>

          {selectedAlert && (
            <div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-xs text-muted-foreground">
                    Alert Type
                  </span>
                  <strong className="mt-1 block text-sm text-foreground">
                    {selectedAlert.type}
                  </strong>
                </div>
                <div>
                  <span className="text-xs text-muted-foreground">
                    Location
                  </span>
                  <strong className="mt-1 block text-sm text-foreground">
                    {selectedAlert.location}
                  </strong>
                </div>
                <div>
                  <span className="text-xs text-muted-foreground">
                    Severity
                  </span>
                  <div className="mt-1">
                    <SeverityBadge level={selectedAlert.severity} />
                  </div>
                </div>
                <div>
                  <span className="text-xs text-muted-foreground">
                    Status
                  </span>
                  <div className="mt-1">
                    <StatusBadge status={selectedAlert.status} />
                  </div>
                </div>
              </div>

              <div className="mt-5 rounded-md border border-border bg-muted/50 p-4">
                <strong className="mb-1.5 block text-sm text-foreground">
                  Intelligence Summary
                </strong>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {selectedAlert.description}
                </p>
              </div>
            </div>
          )}

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setSelectedAlert(null)}
            >
              Close
            </Button>
            {selectedAlert?.status === "unacknowledged" && (
              <Button
                onClick={() => updateAlert(selectedAlert.id, "acknowledged")}
              >
                Acknowledge Alert
              </Button>
            )}
            {selectedAlert?.status === "acknowledged" && (
              <Button
                className="bg-green-700 hover:bg-green-800"
                onClick={() => updateAlert(selectedAlert.id, "resolved")}
              >
                Resolve Alert
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}